version: "3.7"

services:

  step-ca:
    image: smallstep/step-ca
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./data/step:/home/step
    # network_mode: "host"
    